name = "hackathon-sokuseki-team1-backend"
main = "src/worker.js"
compatibility_date = "2026-03-14"

[[d1_databases]]
binding = "DB"
database_name = "hackathon-sokuseki-team1-db"
database_id = "3ca5188c-6295-48e5-bc4d-a4c145982e4d"
migrations_dir = "migrations"

[assets]
directory = "../dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
